apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "higress-console.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "higress-console.labels" . | nindent 4 }}
data:
---
