{{- if .Values.o11y.enabled }}
{{- $appName := (include "higress-console-promtail.name" .) }}
{{- $config := .Values.o11y.promtail }}
{{- $port := $config.port -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
data:
  promtail.yaml: |
    server:
      log_level: info
      http_listen_port: {{ $port }}

    clients:
    - url: http://{{ include "higress-console-loki.name" .}}:3100/loki/api/v1/push

    positions:
      filename: /var/log/promtail-positions.yaml
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: access-logs
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Release.Namespace }}
        selectors:
        - role: pod
          label: {{ $config.gatewayLabelSelector }}
      pipeline_stages:
      - drop:
          expression: "\\s+\\{"
      - json:
          expressions:
            log:
      - output:
          source: log
      - json:
          expressions:
            authority:
            method:
            path:
            protocol:
            request_id:
            response_code:
            response_flags:
            route_name:
            trace_id:
            upstream_cluster:
            upstream_host:
            upstream_transport_failure_reason:
            user_agent:
            x_forwarded_for:
          drop_malformed: true
      - labels:
          authority:
          method:
          path:
          protocol:
          request_id:
          response_code:
          response_flags:
          route_name:
          trace_id:
          upstream_cluster:
          upstream_host:
          upstream_transport_failure_reason:
          user_agent:
          x_forwarded_for:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_name
          target_label: job
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $appName }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
      - name: promtail
        image: {{ $config.image.repository }}:{{ $config.image.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/promtail/promtail.yaml
        env:
        - name: 'HOSTNAME'
          valueFrom:
            fieldRef:
              fieldPath: 'spec.nodeName'
        ports:
        - containerPort: {{ $port }}
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: {{ $port }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: "/etc/promtail"
        - name: log
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      serviceAccountName: {{ $appName }}
      securityContext:
        {{- toYaml .Values.o11y.promtail.securityContext | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name:  {{ $appName }}
      - name: log
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- end }}