{{- $existedSecret := (lookup "v1" "Secret" .Release.Namespace (include "higress-console.name" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "higress-console.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  adminUsername: {{ .Values.admin.username | b64enc }} 
  adminDisplayName: {{ .Values.admin.displayName | b64enc }} 
{{- $password := .Values.admin.password.value }}
{{- $key := "" }}
{{- $iv := "" }}
{{- if $existedSecret }}
{{-   $password = $existedSecret.data.adminPassword | b64dec }}
{{-   $key = $existedSecret.data.key }}
{{-   $iv = $existedSecret.data.iv }}
{{- end}}
{{- if not $password }}
{{-   $passwordLength := int (default 8 .Values.admin.password.length) }}
{{-   $password = randAlphaNum $passwordLength | nospace }}
{{- end }}
{{- if not $key }}
{{-   $key = randAscii 32 | b64enc }}
{{- end }}
{{- if not $iv }}
{{-   $iv = randAscii 16 | b64enc }}
{{- end }}
  adminPassword: {{ $password | b64enc }}
  key: {{ $key }}
  iv: {{ $iv }}
