/*
 * Copyright (c) 2022-2023 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.alibaba.higress.console.service;

import com.alibaba.higress.console.constant.KubernetesConstants;
import com.alibaba.higress.console.controller.dto.CommonPageQuery;
import com.alibaba.higress.console.controller.dto.PaginatedResult;
import com.alibaba.higress.console.controller.dto.ServiceSource;
import com.alibaba.higress.console.controller.exception.AlreadyExistedException;
import com.alibaba.higress.console.controller.exception.BusinessException;
import com.alibaba.higress.console.controller.exception.NotFoundException;
import com.alibaba.higress.console.service.kubernetes.KubernetesClientService;
import com.alibaba.higress.console.service.kubernetes.KubernetesModelConverter;
import com.alibaba.higress.console.service.kubernetes.crd.mcp.V1McpBridge;
import com.alibaba.higress.console.service.kubernetes.crd.mcp.V1RegistryConfig;
import io.kubernetes.client.openapi.ApiException;
import org.apache.commons.lang3.StringUtils;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.util.CollectionUtils;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class ServiceSourceServiceImpl implements ServiceSourceService {

    private KubernetesClientService kubernetesClientService;
    private KubernetesModelConverter kubernetesModelConverter;

    @Resource
    public void setKubernetesClientService(KubernetesClientService kubernetesClientService) {
        this.kubernetesClientService = kubernetesClientService;
    }

    @Resource
    public void setKubernetesModelConverter(KubernetesModelConverter kubernetesModelConverter) {
        this.kubernetesModelConverter = kubernetesModelConverter;
    }

    @Override
    public PaginatedResult<ServiceSource> list(CommonPageQuery query) {
        V1McpBridge v1McpBridge = kubernetesClientService.getV1McpBridge(KubernetesConstants.MCP_BRIDGE_NAME);
        List<ServiceSource> serviceSources = new ArrayList<>();
        if(null != v1McpBridge && !CollectionUtils.isEmpty(v1McpBridge.getSpec().getRegistries())){
            serviceSources = v1McpBridge.getSpec().getRegistries().stream().map(kubernetesModelConverter::v1RegistryConfig2ServiceSource).collect(Collectors.toList());
        }
        return PaginatedResult.createFromFullList(serviceSources, query);
    }

    @Override
    public ServiceSource addOrUpdate(ServiceSource serviceSource) {
        try {
            V1McpBridge v1McpBridge = kubernetesClientService.getV1McpBridge(KubernetesConstants.MCP_BRIDGE_NAME);
            if(null == v1McpBridge){
                v1McpBridge = new V1McpBridge();
                KubernetesModelConverter.initV1McpBridge(v1McpBridge);
                KubernetesModelConverter.addV1McpBridgeRegistry(v1McpBridge,serviceSource);
                kubernetesClientService.addV1McpBridge(v1McpBridge);
            }else {
                KubernetesModelConverter.addV1McpBridgeRegistry(v1McpBridge,serviceSource);
                kubernetesClientService.updateV1McpBridge(v1McpBridge);
            }
        } catch (ApiException e) {
            if (e.getCode() == HttpStatus.CONFLICT.value()) {
                throw new AlreadyExistedException();
            }
            throw new BusinessException(
                    "Error occurs when add the serviceSource generated by serviceSource with name: " + serviceSource.getName(), e);
        }
        return serviceSource;
    }

    @Override
    public void delete(String name) {
        try {
            V1McpBridge v1McpBridge = kubernetesClientService.getV1McpBridge(KubernetesConstants.MCP_BRIDGE_NAME);
            if(null == v1McpBridge){
                throw new NotFoundException("V1McpBridge not found");
            }
            KubernetesModelConverter.removeV1McpBridgeRegistry(v1McpBridge,name);
            kubernetesClientService.updateV1McpBridge(v1McpBridge);
        } catch (ApiException e) {
            throw new BusinessException("Error occurs when deleting the serviceSource with name: " + name, e);
        }
    }

    @Override
    public ServiceSource query(String name) throws BusinessException {
        V1McpBridge v1McpBridge = kubernetesClientService.getV1McpBridge(KubernetesConstants.MCP_BRIDGE_NAME);
        if(null == v1McpBridge || CollectionUtils.isEmpty(v1McpBridge.getSpec().getRegistries())){
            return null;
        }
        Optional<V1RegistryConfig> op = v1McpBridge.getSpec().getRegistries().stream().filter(r -> StringUtils.isNotBlank(r.getName()) && name.equals(r.getName())).findFirst();
        if(op.isPresent()){
            return op.map(kubernetesModelConverter::v1RegistryConfig2ServiceSource).get();
        }
        return null;
    }

    @Override
    public ServiceSource add(ServiceSource serviceSource) {
        try {
            V1McpBridge v1McpBridge = kubernetesClientService.getV1McpBridge(KubernetesConstants.MCP_BRIDGE_NAME);
            if(null == v1McpBridge){
                v1McpBridge = new V1McpBridge();
                KubernetesModelConverter.initV1McpBridge(v1McpBridge);
                KubernetesModelConverter.addV1McpBridgeRegistry(v1McpBridge,serviceSource);
                kubernetesClientService.addV1McpBridge(v1McpBridge);
            }else {
                Optional<V1RegistryConfig> op = v1McpBridge.getSpec().getRegistries().stream().filter(r -> StringUtils.isNotBlank(r.getName()) && r.getName().equals(serviceSource.getName())).findFirst();
                if(op.isPresent()){
                    throw new AlreadyExistedException();
                }
                KubernetesModelConverter.addV1McpBridgeRegistry(v1McpBridge,serviceSource);
                kubernetesClientService.updateV1McpBridge(v1McpBridge);
            }
        } catch (ApiException e) {
            if (e.getCode() == HttpStatus.CONFLICT.value()) {
                throw new AlreadyExistedException();
            }
            throw new BusinessException(
                    "Error occurs when add the serviceSource generated by serviceSource with name: " + serviceSource.getName(), e);
        }
        return serviceSource;
    }
}
