/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.higress.sdk.service.kubernetes.crd.gatewayapi.httproute;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * HTTPRouteRule defines semantics for matching an HTTP request based on conditions (matches), processing it (filters), and forwarding the request to an API object (backendRefs).
 */
@Data
public class V1HTTPRouteSpecRules {
  public static final String SERIALIZED_NAME_BACKEND_REFS = "backendRefs";
  @SerializedName(SERIALIZED_NAME_BACKEND_REFS)
  private List<V1HTTPRouteSpecBackendRefs> backendRefs = null;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private List<V1HTTPRouteSpecFilters> filters = null;

  public static final String SERIALIZED_NAME_MATCHES = "matches";
  @SerializedName(SERIALIZED_NAME_MATCHES)
  private List<V1HTTPRouteSpecMatches> matches = null;

  public V1HTTPRouteSpecRules addBackendRefsItem(V1HTTPRouteSpecBackendRefs backendRefsItem) {
    if (this.backendRefs == null) {
      this.backendRefs = new ArrayList<>();
    }
    this.backendRefs.add(backendRefsItem);
    return this;
  }

  public V1HTTPRouteSpecRules addFiltersItem(V1HTTPRouteSpecFilters filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }


  public V1HTTPRouteSpecRules addMatchesItem(V1HTTPRouteSpecMatches matchesItem) {
    if (this.matches == null) {
      this.matches = new ArrayList<>();
    }
    this.matches.add(matchesItem);
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HTTPRouteSpecRules v1HTTPRouteSpecRules = (V1HTTPRouteSpecRules) o;
    return Objects.equals(this.backendRefs, v1HTTPRouteSpecRules.backendRefs) &&
        Objects.equals(this.filters, v1HTTPRouteSpecRules.filters) &&
        Objects.equals(this.matches, v1HTTPRouteSpecRules.matches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backendRefs, filters, matches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HTTPRouteSpecRules {\n");
    sb.append("    backendRefs: ").append(toIndentedString(backendRefs)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    matches: ").append(toIndentedString(matches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

