/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.higress.sdk.service.kubernetes.crd.gatewayapi.httproute;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResponseHeaderModifier defines a schema for a filter that modifies response headers.   Support: Extended
 */
@Data
public class V1HTTPRouteSpecResponseHeaderModifier {
  public static final String SERIALIZED_NAME_ADD = "add";
  @SerializedName(SERIALIZED_NAME_ADD)
  private List<V1HTTPRouteSpecRequestHeaderModifierAdd> add = null;

  public static final String SERIALIZED_NAME_REMOVE = "remove";
  @SerializedName(SERIALIZED_NAME_REMOVE)
  private List<String> remove = null;

  public static final String SERIALIZED_NAME_SET = "set";
  @SerializedName(SERIALIZED_NAME_SET)
  private List<V1HTTPRouteSpecRequestHeaderModifierAdd> set = null;

  public V1HTTPRouteSpecResponseHeaderModifier addAddItem(V1HTTPRouteSpecRequestHeaderModifierAdd addItem) {
    if (this.add == null) {
      this.add = new ArrayList<>();
    }
    this.add.add(addItem);
    return this;
  }

  public V1HTTPRouteSpecResponseHeaderModifier addRemoveItem(String removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

  public V1HTTPRouteSpecResponseHeaderModifier addSetItem(V1HTTPRouteSpecRequestHeaderModifierAdd setItem) {
    if (this.set == null) {
      this.set = new ArrayList<>();
    }
    this.set.add(setItem);
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1HTTPRouteSpecResponseHeaderModifier v1HttpRouteSpecResponseHeaderModifier = (V1HTTPRouteSpecResponseHeaderModifier) o;
    return Objects.equals(this.add, v1HttpRouteSpecResponseHeaderModifier.add) &&
        Objects.equals(this.remove, v1HttpRouteSpecResponseHeaderModifier.remove) &&
        Objects.equals(this.set, v1HttpRouteSpecResponseHeaderModifier.set);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, remove, set);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1HTTPRouteSpecResponseHeaderModifier {\n");
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

