/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.higress.sdk.service.kubernetes.crd.gatewayapi.gateways;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Spec defines the desired state of Gateway.
 */
@Data
public class V1GatewaySpec {
  public static final String SERIALIZED_NAME_ADDRESSES = "addresses";
  @SerializedName(SERIALIZED_NAME_ADDRESSES)
  private List<V1GatewaySpecAddresses> addresses = null;

  public static final String SERIALIZED_NAME_GATEWAY_CLASS_NAME = "gatewayClassName";
  @SerializedName(SERIALIZED_NAME_GATEWAY_CLASS_NAME)
  private String gatewayClassName;

  public static final String SERIALIZED_NAME_LISTENERS = "listeners";
  @SerializedName(SERIALIZED_NAME_LISTENERS)
  private List<V1GatewaySpecListeners> listeners = new ArrayList<>();

  public V1GatewaySpec addAddressesItem(V1GatewaySpecAddresses addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<>();
    }
    this.addresses.add(addressesItem);
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GatewaySpec v1GatewaySpec = (V1GatewaySpec) o;
    return Objects.equals(this.addresses, v1GatewaySpec.addresses) &&
        Objects.equals(this.gatewayClassName, v1GatewaySpec.gatewayClassName) &&
        Objects.equals(this.listeners, v1GatewaySpec.listeners);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, gatewayClassName, listeners);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1GatewaySpec {\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    gatewayClassName: ").append(toIndentedString(gatewayClassName)).append("\n");
    sb.append("    listeners: ").append(toIndentedString(listeners)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

