/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alibaba.higress.sdk.service.kubernetes.crd.gatewayapi.gateways;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ListenerStatus is the status associated with a Listener.
 */
@Data
public class V1GatewayStatusListeners {
  public static final String SERIALIZED_NAME_ATTACHED_ROUTES = "attachedRoutes";
  @SerializedName(SERIALIZED_NAME_ATTACHED_ROUTES)
  private Integer attachedRoutes;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1GatewayStatusConditions> conditions = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUPPORTED_KINDS = "supportedKinds";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_KINDS)
  private List<V1GatewaySpecAllowedRoutesKinds> supportedKinds = new ArrayList<>();

  public V1GatewayStatusListeners addConditionsItem(V1GatewayStatusConditions conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

  public V1GatewayStatusListeners addSupportedKindsItem(V1GatewaySpecAllowedRoutesKinds supportedKindsItem) {
    this.supportedKinds.add(supportedKindsItem);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GatewayStatusListeners v1GatewayStatusListeners = (V1GatewayStatusListeners) o;
    return Objects.equals(this.attachedRoutes, v1GatewayStatusListeners.attachedRoutes) &&
        Objects.equals(this.conditions, v1GatewayStatusListeners.conditions) &&
        Objects.equals(this.name, v1GatewayStatusListeners.name) &&
        Objects.equals(this.supportedKinds, v1GatewayStatusListeners.supportedKinds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachedRoutes, conditions, name, supportedKinds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1GatewayStatusListeners {\n");
    sb.append("    attachedRoutes: ").append(toIndentedString(attachedRoutes)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportedKinds: ").append(toIndentedString(supportedKinds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

